### PR TITLE
Autopep

### PR DESCRIPTION
**Pull request by FelixAbrahamsson**
Will mostly just take care of some whitespace. Doesn't deal with single/double quotes or line length, in general very conservative.

Before formatting
```python
import pandas as pd



df = (
    pd.DataFrame(dict(a=[1,2,3]))
    .assign(b = lambda df: df['a'] * 5).assign(c=lambda df: df['b'] * 5)
)
def a():


    pass



def b():
    pass



```

after formatting
```python
import pandas as pd


df = (
    pd.DataFrame(dict(a=[1, 2, 3]))
    .assign(b=lambda df: df['a'] * 5).assign(c=lambda df: df['b'] * 5)
)


def a():

    pass


def b():
    pass

```

### CODE REVIEW

**Comment by JoarGruneau** [comment]
How does this compare to yapf and black?
Do you have more examples of more tricky formatting like nested dicts?
Think it is time to decide on one python formatter and then use it on all projects :D.

**Comment by samedii** [comment]
Felix has done a lot of research and sadly the formatters seem awful (imo)

**Comment by FelixAbrahamsson** [comment]
So YAPF doesn't deal well with chained operations and it doesn't seem like anyone has a reasonable workaround/solution
https://github.com/google/yapf/issues/348
https://github.com/google/yapf/issues/617

To us that's kind of a dealbreaker. Black from what I remember can handle that case but had some other cases where it would format things in a pretty ugly way. I don't remember exactly what types of cases that were though, maybe @samedii has some examples?

Anyway, I've now realized that autopep is reading the flake8 config file along with the pyproject.toml config, even though it claims that pyproject should take precedence (I thought I had this working already but apparently not). For some reason the flake8 config is still affecting the behavior in an incompatible way, e.g. `select = C,E,F,W,B,B950` in flake8 makes it ignore the `ignore = "E501"` line in pyproject. The only workaround I can see is using the flake8 config file for both flake8 and autopep (not very nice, would be good to have flake8 as a linter that can be more strict and autopep as a formatter being more lenient). I'll try and see if I can find a solution to this.

**Comment by FelixAbrahamsson** [comment]
Seems like just removing the `select` config in flake8 makes everything work ok. `flake8` is still picking up all errors/warnings.

**Comment by samedii** [comment]
We should close this now since we are using black + manual disable?

**Pull request closed without merging**
